import "dotenv/config"

const SECRET_KEY_REGIS = process.env.SECRET_KEY_REGIS || ""

const GMAIL_EMAIL = process.env.GMAIL_EMAIL || ""
const GMAIL_APP_PASS = process.env.GMAIL_APP_PASS

const BASE_WEB_URL = process.env.BASE_WEB_URL || ""

const SECRET_KEY_ACCESS = process.env.SECRET_KEY_ACCESS || ""
const SECRET_KEY_REFRESH = process.env.SECRET_KEY_REFRESH || ""

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID || "";
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET || ""

const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY || "";
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET || "";
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME || "";

export {
    SECRET_KEY_REGIS,
    GMAIL_EMAIL,
    GMAIL_APP_PASS,
    BASE_WEB_URL,
    SECRET_KEY_ACCESS,
    SECRET_KEY_REFRESH,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_CLOUD_NAME
}